"""Alembic environment, async.

Async rather than sync so there is one database driver in the project instead of
two. Adding psycopg2 purely for migrations means a second driver to install, a
second connection string to keep in sync, and a second set of type behaviours to
be surprised by.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from citysignal.config import get_settings
from citysignal.db import models  # noqa: F401 - import registers the models on Base.metadata
from citysignal.db.base import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().async_database_url)
target_metadata = Base.metadata


def include_object(
    obj: object, name: str | None, type_: str, *args: object, **kwargs: object
) -> bool:
    """Keep PostGIS's own bookkeeping out of autogenerate.

    CREATE EXTENSION postgis creates spatial_ref_sys and a few views. Without
    this filter, every autogenerated migration proposes dropping them.
    """
    if type_ == "table" and name in {"spatial_ref_sys", "geometry_columns", "geography_columns"}:
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
        # Alembic's own version table gets a schema-qualified name so a future
        # multi-schema layout does not silently create a second one.
        version_table="alembic_version",
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
