#!/usr/bin/env bash
#
# Regenerate services/api/constraints-ci.txt — the version set CI installs.
# Run it through `make constraints`, never by hand from a different directory.
#
# It resolves inside a linux/amd64 python:3.12 container rather than freezing
# services/api/.venv, and that is not fastidiousness. Measured 2026-08-05, the
# two environments disagree about eleven distributions, and one of the
# disagreements cannot be reconciled at all: onnxruntime resolves to 1.28.0 on
# linux and the newest release with a macOS x86_64 wheel is 1.23.2. A file
# frozen from the developer's machine would pin CI to a version that does not
# exist for it.
#
# The container gets a two-file stand-in for the package — pyproject.toml and an
# empty nightshift/__init__.py — rather than the repo. Mounting services/api
# would drag .venv (a gigabyte, mostly onnxruntime) through the copy and let a
# root-owned *.egg-info back out into the working tree.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
target="$repo_root/services/api/constraints-ci.txt"
image="python:3.12-slim"

if ! docker version --format '{{.Server.Version}}' > /dev/null 2>&1; then
  echo "error: docker is not running, and this must resolve on linux — see the comment in $(basename "$0")" >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/nightshift"
cp "$repo_root/services/api/pyproject.toml" "$work/pyproject.toml"
touch "$work/nightshift/__init__.py" "$work/nightshift/py.typed"

echo "==> resolving services/api[dev] inside $image (linux/amd64)"
resolved="$work/freeze.txt"
docker run --rm --platform linux/amd64 -v "$work:/build" -w /build "$image" \
  sh -c 'python -m pip install --upgrade pip -q && pip install -q ".[dev]" && pip freeze --exclude-editable' \
  > "$resolved"

# `pip freeze --exclude-editable` still lists a non-editable local install, and
# in the container that is nightshift itself, pointing at a path that exists
# nowhere else. It is the package being constrained, not one of its constraints.
{
  cat <<'HEADER'
# CI's pinned dependency set. Generated by scripts/regenerate_constraints.sh —
# run `make constraints`; do not hand-edit.
#
# Why this file exists (ADR 0016): CI installed unpinned, and on 2026-08-05
# alembic 1.19.0 shipped a new check-constraint comparator that turned the
# migrations job red on a branch which had not touched a migration in a week.
# The drift it found was real, so the answer is not "pin and stop looking" —
# .github/workflows/dependency-canary.yml still installs unpinned on a schedule
# and reports what moved. This file is only for the jobs that gate a merge.
#
# This file is CI's and not a developer's. It is resolved for linux/amd64, and
# several of these versions do not exist for macOS: measured 2026-08-05, the
# newest onnxruntime with a macOS x86_64 wheel is 1.23.2, and this file pins
# 1.28.0. Pointing PIP_CONSTRAINT at it locally fails to install.
#
# Versions, not hashes. This defends against an unexpected release, not against
# a compromised one; that would need --require-hashes, and it is not what went
# wrong here.
HEADER
  grep -v '^nightshift @ ' "$resolved"
} > "$target"

count="$(grep -cvE '^\s*(#|$)' "$target")"
echo "==> wrote $target — $count distributions pinned"
echo "    commit it, and CI's 'the pin covers everything that got installed' step will check it"
