"""board_poll_state

What polling knows about each board: the stored ETag, the tier, when it is
next due. ADR 0007 and ``docs/architecture/conditional-polling.md`` §6.

Written by hand rather than autogenerated. Autogenerate has emitted a defect
that would fail at upgrade time rather than at review in both of the last two
migrations here — an unimported ``nightshift.db.types`` in ``0003``, and three
separate problems in ``0002``, including a ``CREATE TYPE`` for an enum that
already existed. The note at the head of ``0002`` is load-bearing, not
historical, and the cost of writing thirty lines by hand is lower than the cost
of reviewing thirty generated ones carefully enough.

The ``board_tier`` enum is created explicitly in ``upgrade`` and dropped
explicitly in ``downgrade``. A downgrade that forgets ``DROP TYPE`` leaves the
type behind, and the next upgrade then fails on a type that already exists —
which is exactly the failure ``0002`` records.

No data migration. Rows are created by ``sync_board_poll_state`` from the
registry on the first scheduler tick, due immediately, which is the correct
starting state for a board nobody has polled: no ETag, warm tier, poll now.

Revision ID: 0004_board_poll_state
Revises: 0003_source_updated_at
Create Date: 2026-08-03 02:10:00+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import nightshift.db.types

revision: str = "0004_board_poll_state"
down_revision: str | None = "0003_source_updated_at"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Declared once and reused for both the CREATE TYPE and the column, so the two
#: cannot drift into disagreeing about the member list.
BOARD_TIER = postgresql.ENUM("hot", "warm", name="board_tier", create_type=False)


def upgrade() -> None:
    BOARD_TIER.create(op.get_bind(), checkfirst=False)

    op.create_table(
        "board_poll_state",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("ats", sa.String(length=50), nullable=False),
        sa.Column("token", sa.String(length=200), nullable=False),
        # 500: the three providers measured 36, 37 and 78 characters on
        # 2026-08-02, and Ashby's is content-addressed so it grows with what it
        # hashes. A truncated ETag never matches, so every poll becomes a full
        # fetch and nothing says why.
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("parser_version", sa.String(length=20), nullable=False),
        sa.Column("tier", BOARD_TIER, nullable=False, server_default="warm"),
        sa.Column(
            "next_poll_at", nightshift.db.types.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "last_polled_at", nightshift.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "last_success_at", nightshift.db.types.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "created_at",
            nightshift.db.types.UTCDateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            nightshift.db.types.UTCDateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name="fk_board_poll_state_source_id_sources",
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("ats", "token", name="uq_board_poll_state_ats_token"),
    )
    op.create_index(
        "ix_board_poll_state_next_poll_at", "board_poll_state", ["next_poll_at"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_board_poll_state_next_poll_at", table_name="board_poll_state")
    op.drop_table("board_poll_state")
    # Not optional. Leaving the type behind makes the next upgrade fail on a
    # type that already exists, which is the defect 0002 records at its head.
    BOARD_TIER.drop(op.get_bind(), checkfirst=False)
