"""Two partial indexes for M2d's daily queue.

Revision ID: 0010_queue_indexes
Revises: 0009_profile_and_resumes
Create Date: 2026-08-04 05:05:36.742132+00:00

Both are partial, and both are partial for the same reason: the queue asks a
question about a *subset* of `application_events`, and indexing the rest would
be dead weight on the busiest write path in the schema.

`ix_application_events_user_activity` serves "when did this person last touch
this application?", which excludes system events by design — see
`docs/architecture/command-center.md` §7.2. `ix_application_events_interviews`
serves "interviews in the next fortnight", which scans by time across every
application and so cannot use the `(application_id, occurred_at)` index whose
leading column is the wrong one.

Nothing here touches a column, so `alembic check` drift is the only risk and
`op.create_index` is the only operation.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0010_queue_indexes"
down_revision: str | None = "0009_profile_and_resumes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_application_events_interviews",
        "application_events",
        ["occurred_at"],
        unique=False,
        postgresql_where=sa.text("event_type = 'interview_scheduled'"),
    )
    op.create_index(
        "ix_application_events_user_activity",
        "application_events",
        ["application_id", "occurred_at"],
        unique=False,
        postgresql_where=sa.text("actor = 'user'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_application_events_user_activity",
        table_name="application_events",
        postgresql_where=sa.text("actor = 'user'"),
    )
    op.drop_index(
        "ix_application_events_interviews",
        table_name="application_events",
        postgresql_where=sa.text("event_type = 'interview_scheduled'"),
    )
    # ### end Alembic commands ###
