"""The denominator, and the field a span points into.

Revision ID: 0017_match_score_denominator
Revises: 0016_match_results
Create Date: 2026-08-09

M3c Task 8. Two columns `0016_match_results` could not have known it needed,
both found by implementing the thing that fills them — which is why they land
here rather than being folded back into a migration that has already run.

**`match_results.assessed_out_of`** (`matching.md` §5.1.2). The score is out of
what could be assessed, not out of 100: 26 of the 60 labeled postings name no
required technology, and skill overlap and project evidence both read that list,
so on 43% of the corpus half the available score cannot be computed. §5.1.1
decided such a posting is scored out of 50 rather than penalised 50.

The denominator cannot be recovered from the six component columns. A component
that scored zero and a component the posting said too little to assess **both
store `0`**, and telling those two apart is the entire content of §5.1.1. §4.2
precomputes the score because "a sort needs the value in the database"; the
ranked list sorts on the fraction, so the denominator is part of that value.

**`match_evidence.job_span_field`** (§4.3). Every span elsewhere in this system
indexes into `jobs.description_text`. Role relevance is decided on the **title**
— `role_classification.TextSpan` has carried the field it read since Task 3 —
and `match_evidence_span_must_quote` was written checking `description_text`
alone. Left as it was, the first real role evidence row would be rejected for
not quoting a string it never claimed to come from, and the only way to make it
pass would be to stop storing the span. The trigger is rewritten below to read
the field the row names.

**Existing rows are deleted rather than backfilled**, in both directions. There
are none — nothing wrote these tables before Task 8 — so this costs nothing
today, and choosing it deliberately matters more than what it costs. A row from
before this revision has no honest `assessed_out_of`: writing `100` would assert
that every component was assessable, which is exactly the claim §5.1.1 exists to
stop anyone making by default. The same going down: a title span whose field
column has just been dropped is an offset into a string nobody can name, and the
quoting trigger would check it against the description and reject it. Deleting
is what this table already does when an input moves (§4.2) — an absent score
reads as not-yet-computed, which is true, and the recompute task rebuilds it.

Written by hand rather than autogenerated. Autogenerate cannot see the trigger
body, would not emit `CREATE TYPE`/`DROP TYPE` for `job_text_field`
(M2c finding 3, fifth appearance), and would have added `assessed_out_of` as
nullable or with a fabricated default.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017_match_score_denominator"
down_revision: str | None = "0016_match_results"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Duplicated from `nightshift.db.base.JobTextField` for the reason
#: `0015_internship_season` records: a migration that imports a model stops
#: describing the schema as of its own revision and starts describing today's.
#: `test_enum_vocabularies_agree` is what makes the copy safe.
JOB_TEXT_FIELD_VALUES = ("title", "description_text")

#: The span and its three companions. The field is part of the unit for the same
#: reason the offsets are: half a span cannot be checked against anything, and
#: offsets with no named string are a span whose substrate is a guess.
_SPAN_TRAVELS_TOGETHER = (
    "(job_span_text IS NULL) = (job_char_start IS NULL)"
    " AND (job_char_start IS NULL) = (job_char_end IS NULL)"
    " AND (job_char_end IS NULL) = (job_span_field IS NULL)"
)
_SPAN_TRAVELS_TOGETHER_WITHOUT_FIELD = (
    "(job_span_text IS NULL) = (job_char_start IS NULL)"
    " AND (job_char_start IS NULL) = (job_char_end IS NULL)"
)

#: The quoting guard, with a hole where the lookup goes. The `SELECT` is the
#: only thing that differs between the two directions, and writing both from
#: one string is what stops the downgrade drifting into a subtly different
#: check than the one it is restoring. Substituted by `str.replace` rather
#: than `%`-formatting because plpgsql's own `RAISE` placeholders are `%`.
_SPAN_MUST_QUOTE = """
CREATE OR REPLACE FUNCTION nightshift_evidence_span_must_quote_the_text()
RETURNS trigger AS $$
DECLARE
    source_text text;
    source_name text;
BEGIN
    IF NEW.job_span_text IS NULL THEN
        RETURN NEW;
    END IF;
    __SELECT__
    IF source_text IS NULL THEN
        RAISE EXCEPTION
            'match_result % scores a job whose % is null',
            NEW.match_result_id, source_name;
    END IF;
    IF NEW.job_char_end <= NEW.job_char_start THEN
        RETURN NEW;
    END IF;
    IF NEW.job_char_end > length(source_text) THEN
        RAISE EXCEPTION
            'span [%,%) runs past the % characters of the job %',
            NEW.job_char_start, NEW.job_char_end, length(source_text), source_name;
    END IF;
    IF substring(source_text FROM NEW.job_char_start + 1
                 FOR NEW.job_char_end - NEW.job_char_start) <> NEW.job_span_text THEN
        RAISE EXCEPTION
            'span [%,%) does not quote the job %',
            NEW.job_char_start, NEW.job_char_end, source_name;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

#: Reads the column the row names. A null `job_span_field` beside a non-null
#: span returns early rather than raising here: the CHECK constraint above says
#: that combination is illegal and says so with the constraint's own name, and
#: BEFORE ROW triggers fire first — the same early return, and the same reason,
#: as the inverted-span case below it.
_SELECT_BY_FIELD = """
    IF NEW.job_span_field IS NULL THEN
        RETURN NEW;
    END IF;
    source_name := NEW.job_span_field::text;
    SELECT CASE NEW.job_span_field
             WHEN 'title' THEN jobs.title
             WHEN 'description_text' THEN jobs.description_text
           END
      INTO source_text
      FROM match_results
      JOIN jobs ON jobs.id = match_results.job_id
     WHERE match_results.id = NEW.match_result_id;
"""

#: What `0016_match_results` had: one column, named in prose.
_SELECT_DESCRIPTION_ONLY = """
    source_name := 'description_text';
    SELECT jobs.description_text INTO source_text
      FROM match_results
      JOIN jobs ON jobs.id = match_results.job_id
     WHERE match_results.id = NEW.match_result_id;
"""


def upgrade() -> None:
    # Nothing has ever written these tables, so this deletes nothing today. See
    # the module docstring for why it is a delete and not a backfill.
    op.execute("DELETE FROM match_results")

    op.execute(
        "CREATE TYPE job_text_field AS ENUM ("
        + ", ".join(f"'{value}'" for value in JOB_TEXT_FIELD_VALUES)
        + ")"
    )
    op.add_column(
        "match_evidence",
        sa.Column(
            "job_span_field",
            postgresql.ENUM(*JOB_TEXT_FIELD_VALUES, name="job_text_field", create_type=False),
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("ck_match_evidence_the_job_span_travels_together"),
        "match_evidence",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_match_evidence_the_job_span_travels_together"),
        "match_evidence",
        _SPAN_TRAVELS_TOGETHER,
    )
    op.execute(_SPAN_MUST_QUOTE.replace("__SELECT__", _SELECT_BY_FIELD))

    # NOT NULL with no server default: every insert names its own denominator.
    # A default would be a fabricated one, and the whole reason this column
    # exists is that there is no correct default (§5.1.1).
    op.add_column("match_results", sa.Column("assessed_out_of", sa.SmallInteger(), nullable=False))
    op.create_check_constraint(
        op.f("ck_match_results_assessed_out_of_is_a_share_of_one_hundred"),
        "match_results",
        "assessed_out_of >= 0 AND assessed_out_of <= 100",
    )
    op.create_check_constraint(
        op.f("ck_match_results_a_score_never_exceeds_what_was_assessed"),
        "match_results",
        "overall_score <= assessed_out_of",
    )


def downgrade() -> None:
    # Symmetric to the upgrade, and for the stronger reason: a stored title span
    # outlives the column naming it, and the restored trigger would check it
    # against the description.
    op.execute("DELETE FROM match_results")

    op.drop_constraint(
        op.f("ck_match_results_a_score_never_exceeds_what_was_assessed"),
        "match_results",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_match_results_assessed_out_of_is_a_share_of_one_hundred"),
        "match_results",
        type_="check",
    )
    op.drop_column("match_results", "assessed_out_of")

    op.execute(_SPAN_MUST_QUOTE.replace("__SELECT__", _SELECT_DESCRIPTION_ONLY))
    op.drop_constraint(
        op.f("ck_match_evidence_the_job_span_travels_together"),
        "match_evidence",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_match_evidence_the_job_span_travels_together"),
        "match_evidence",
        _SPAN_TRAVELS_TOGETHER_WITHOUT_FIELD,
    )
    op.drop_column("match_evidence", "job_span_field")
    op.execute("DROP TYPE IF EXISTS job_text_field")
