"""job requirements — what a posting asks for, and the characters where it says so

The span trigger here is modelled directly on
``nightshift_resume_span_must_quote_the_text`` in
``20260803_2100_profile_and_resumes.py``: same reasoning (a requirement nobody
can trace back to a sentence is not auditable), same 0-indexed-Python vs.
1-indexed-Postgres ``substring`` offset, different table and column names
(``jobs.description_text`` / ``raw_text`` instead of ``resumes.parsed_text`` /
``quoted_text``).

Autogenerate produced a random hex revision id (``d8dbf30f45cf``) rather than
this project's sequential ``NNNN_name`` convention; renamed by hand to
``0011_job_requirements`` to match ``0001``-``0010``. It did not reproduce the
usual missing-``UTCDateTime``-import defect this time (it emitted
``sa.DateTime(timezone=True)`` directly), and both table
``CheckConstraint``s came through, but it still omitted the enum ``DROP TYPE``
on downgrade — added by hand below, following ``0008_application_tracking``.

A second trigger, added after review: the span trigger on ``job_requirements``
cannot see its parent row change, and ``jobs.description_text`` is rewritten on
every re-poll of a known job by ``_apply_normalized_fields()`` in
``nightshift/domain/ingestion.py`` — reproduced against the dev database, a
requirement quoting "Kotlin" at the right offsets survived a description
rewrite and pointed at the wrong six characters while still claiming
``raw_text='Kotlin'``. ``nightshift_requirements_follow_the_description``
deletes a job's requirements ``AFTER UPDATE OF description_text`` whenever the
text actually changed (``IS DISTINCT FROM``, so a re-poll of an unchanged
board does not throw away work the extractor would only redo). A trigger
rather than a rule in application code, because ingestion writes the column
directly and a guarantee resting on every future writer remembering to call a
helper is not a guarantee.

Revision ID: 0011_job_requirements
Revises: 0010_queue_indexes
Create Date: 2026-08-04 13:07:59.831103+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0011_job_requirements"
down_revision: str | None = "0010_queue_indexes"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_requirements",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "degree",
                "graduation_window",
                "years_experience",
                "technology",
                "authorization",
                "enrollment",
                "role_level",
                name="requirement_kind",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=200), nullable=False),
        sa.Column("raw_text", sa.String(length=500), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column(
            "necessity",
            sa.Enum("required", "preferred", "mentioned", name="requirement_necessity"),
            nullable=False,
        ),
        sa.Column("has_equivalence", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("extractor_version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_end > char_start", name=op.f("ck_job_requirements_span_runs_forwards")
        ),
        sa.CheckConstraint(
            "char_start >= 0", name=op.f("ck_job_requirements_char_start_is_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_requirements_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirements")),
        sa.UniqueConstraint(
            "job_id", "kind", "value", "char_start", name="uq_job_requirements_span"
        ),
    )
    op.create_index("ix_job_requirements_job_id", "job_requirements", ["job_id"], unique=False)
    # ### end Alembic commands ###

    # A requirement nobody can trace back to a sentence is not auditable, so
    # the span it claims must literally quote the job's description text —
    # enforced here because the text it must compare against lives in another
    # table, which a CHECK constraint cannot see.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION nightshift_requirement_span_must_quote_the_text()
        RETURNS trigger AS $$
        DECLARE
            source_text text;
        BEGIN
            SELECT description_text INTO source_text FROM jobs WHERE id = NEW.job_id;
            IF source_text IS NULL THEN
                RAISE EXCEPTION 'job % has no description text', NEW.job_id;
            END IF;
            -- An inverted or empty span is the `span_runs_forwards` CHECK
            -- constraint's job, not this trigger's: BEFORE ROW triggers fire
            -- before constraints are validated (measured directly against
            -- this database — a scratch table with an analogous trigger and
            -- CHECK confirmed the ordering), so a negative FOR count here
            -- would reach `substring()` first and raise Postgres's own
            -- "negative substring length not allowed" instead of the
            -- IntegrityError callers of this table expect for that case.
            IF NEW.char_end <= NEW.char_start THEN
                RETURN NEW;
            END IF;
            IF NEW.char_end > length(source_text) THEN
                RAISE EXCEPTION
                    'span [%,%) runs past the % characters of job %',
                    NEW.char_start, NEW.char_end, length(source_text), NEW.job_id;
            END IF;
            IF substring(source_text FROM NEW.char_start + 1
                         FOR NEW.char_end - NEW.char_start) <> NEW.raw_text THEN
                RAISE EXCEPTION
                    'span [%,%) does not quote the job description',
                    NEW.char_start, NEW.char_end;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER job_requirements_span_must_quote "
        "BEFORE INSERT OR UPDATE ON job_requirements "
        "FOR EACH ROW EXECUTE FUNCTION nightshift_requirement_span_must_quote_the_text()"
    )

    # Requirements are offsets into `description_text`. When that text changes,
    # every existing row points at characters that have moved — so they are
    # deleted rather than left to lie. The extractor repopulates from the new
    # text; an absent requirement is honest, a stale one is not.
    #
    # This is a trigger rather than a rule in `sync_requirements` because
    # ingestion writes the column directly, and a guarantee that depends on
    # every future writer remembering to call a helper is not a guarantee.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION nightshift_requirements_follow_the_description()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.description_text IS DISTINCT FROM OLD.description_text THEN
                DELETE FROM job_requirements WHERE job_id = NEW.id;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        "CREATE TRIGGER jobs_description_change_clears_requirements "
        "AFTER UPDATE OF description_text ON jobs "
        "FOR EACH ROW EXECUTE FUNCTION nightshift_requirements_follow_the_description()"
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS jobs_description_change_clears_requirements ON jobs")
    op.execute("DROP FUNCTION IF EXISTS nightshift_requirements_follow_the_description()")
    op.execute("DROP TRIGGER IF EXISTS job_requirements_span_must_quote ON job_requirements")
    op.execute("DROP FUNCTION IF EXISTS nightshift_requirement_span_must_quote_the_text()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_requirements_job_id", table_name="job_requirements")
    op.drop_table("job_requirements")
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE, leaving the enums behind and the
    # next upgrade failing with "type already exists" (this bug has bitten
    # this repo before — see 0009_profile_and_resumes).
    for enum_name in ("requirement_necessity", "requirement_kind"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
