"""source_updated_at on source_job_records

Adds the one column ADR 0007's phase-2 diff compares against.

Greenhouse publishes a per-posting ``updated_at`` on its board listing, and it
is the only one of the three providers that does. The diff asks "which listed
postings changed since we last fetched their content", and it needs somewhere
to have stored the answer from last time.

Deliberately on ``source_job_records`` rather than reusing
``jobs.source_updated_at``, which already exists. After a merge one canonical
job carries records from several boards and its timestamp reflects whichever
wrote last, so comparing a board's listing against it would refetch postings
that had not changed and skip ones that had. The record is the per-board fact,
and this is a per-board question.

Autogenerated, then corrected by hand for the same defect the M1b migration
records at its head: autogenerate emitted ``nightshift.db.types.UTCDateTime``
without importing ``nightshift``, which is a ``NameError`` at upgrade time
rather than a review-time complaint. That note in ``0002`` is load-bearing, not
historical — this is the second migration in a row it has caught.

Nullable, with no backfill. NULL means "we have never recorded a timestamp for
this posting", and ``_postings_needing_content`` treats that as "refetch" —
the conservative direction, costing one request rather than risking a change
never being seen. Existing rows are therefore correct as they stand: they were
written before this column existed, so we genuinely do not know.

Revision ID: 0003_source_updated_at
Revises: 0002_canonical_spine
Create Date: 2026-08-03 01:36:43+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import nightshift.db.types

revision: str = "0003_source_updated_at"
down_revision: str | None = "0002_canonical_spine"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "source_job_records",
        sa.Column(
            "source_updated_at",
            nightshift.db.types.UTCDateTime(timezone=True),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("source_job_records", "source_updated_at")
