"""initial ingestion spine

Creates the M0 schema: users, companies, sources, raw source records, canonical
jobs, per-job locations, provenance links, and ingestion runs.

Hand-written rather than autogenerated, for two reasons that matter later:

* The enum types are created and dropped explicitly. Alembic's autogenerate
  emits ``CREATE TYPE`` implicitly on first use and never drops it, which makes
  the downgrade silently non-reversible — the second ``upgrade`` then fails with
  "type already exists". CLAUDE.md §7 requires every migration to be reversible
  and tested in both directions, so the types are managed by hand.
* ``jobs.primary_location_id`` and ``job_locations.job_id`` reference each other.
  The cycle is broken by adding the ``jobs`` side as a separate constraint after
  both tables exist.

Revision ID: 0001_ingestion_spine
Revises:
Create Date: 2026-07-29 22:00:00+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_ingestion_spine"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# name -> labels. Order is irrelevant to Postgres but kept aligned with the
# Python enums in citysignal.db.base so a mismatch is easy to spot in review.
ENUMS: dict[str, tuple[str, ...]] = {
    "location_confidence": ("verified", "approximate", "city_only", "remote", "unknown"),
    "resolution_method": (
        "not_attempted",
        "source_text_parse",
        "nyc_geosearch",
        "nominatim",
        "neighborhood_centroid",
        "manual",
    ),
    "job_status": ("open", "possibly_stale", "unverified", "closed"),
    "source_status": ("active", "missing", "removed"),
    "source_type": ("ats_greenhouse", "ats_lever", "ats_ashby", "government", "fixture"),
    "employment_type": (
        "full_time",
        "part_time",
        "internship",
        "contract",
        "temporary",
        "unknown",
    ),
    "remote_policy": ("on_site", "hybrid", "remote", "unknown"),
    "ingestion_run_status": ("running", "succeeded", "partial", "failed"),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type. ``create_type=False`` prevents a duplicate CREATE."""
    return postgresql.ENUM(*ENUMS[name], name=name, create_type=False)


def upgrade() -> None:
    for name, labels in ENUMS.items():
        postgresql.ENUM(*labels, name=name).create(op.get_bind(), checkfirst=False)

    # -- users -------------------------------------------------------------
    # AMENDMENTS A3: no auth until M5, but the table exists now so every
    # user-owned table added later carries a real FK from its first migration.
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    # -- companies ---------------------------------------------------------
    op.create_table(
        "companies",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.String(length=300), nullable=False),
        sa.Column("normalized_name", sa.String(length=300), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_companies"),
        sa.UniqueConstraint("normalized_name", name="uq_companies_normalized_name"),
    )

    # -- sources -----------------------------------------------------------
    op.create_table(
        "sources",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("source_type", _enum("source_type"), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("priority", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_sources"),
        sa.UniqueConstraint("name", name="uq_sources_name"),
    )

    # -- source_job_records -------------------------------------------------
    op.create_table(
        "source_job_records",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_job_id", sa.String(length=200), nullable=False),
        sa.Column("source_company_key", sa.String(length=200), nullable=False),
        sa.Column("canonical_url", sa.String(length=1000), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("description_hash", sa.String(length=64), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_misses", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("source_status", _enum("source_status"), server_default="active", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name="fk_source_job_records_source_id_sources",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_source_job_records"),
        sa.UniqueConstraint(
            "source_id", "source_job_id", name="uq_source_job_records_source_id_source_job_id"
        ),
    )
    op.create_index("ix_source_job_records_last_seen_at", "source_job_records", ["last_seen_at"])
    op.create_index(
        "ix_source_job_records_source_company_key", "source_job_records", ["source_company_key"]
    )

    # -- jobs --------------------------------------------------------------
    # primary_location_id is added as a column here but its FK is created after
    # job_locations exists, breaking the cycle between the two tables.
    op.create_table(
        "jobs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("company_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("normalized_title", sa.String(length=500), nullable=False),
        sa.Column("role_family", sa.String(length=100), nullable=True),
        sa.Column("seniority", sa.String(length=50), nullable=True),
        sa.Column("employment_type", _enum("employment_type"), server_default="unknown", nullable=False),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=True),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("salary_period", sa.String(length=20), nullable=True),
        sa.Column("application_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_policy", _enum("remote_policy"), server_default="unknown", nullable=False),
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", _enum("job_status"), server_default="open", nullable=False),
        sa.Column("canonical_description_hash", sa.String(length=64), nullable=True),
        sa.Column("primary_location_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max",
            name="ck_jobs_salary_range_ordered",
        ),
        # I3, enforced by the database: a closed job has a closure timestamp,
        # an open one does not. A buggy transition becomes an error, not data.
        sa.CheckConstraint(
            "(status = 'closed') = (closed_at IS NOT NULL)",
            name="ck_jobs_closed_at_matches_status",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name="fk_jobs_company_id_companies", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_jobs"),
    )
    op.create_index("ix_jobs_company_id", "jobs", ["company_id"])
    op.create_index("ix_jobs_status_last_seen_at", "jobs", ["status", "last_seen_at"])
    op.create_index("ix_jobs_normalized_title", "jobs", ["normalized_title"])

    # -- job_locations ------------------------------------------------------
    # AMENDMENTS A2. The check constraints here are invariant I1 in DDL form.
    op.create_table(
        "job_locations",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("raw_text", sa.String(length=500), nullable=False),
        sa.Column("city", sa.String(length=200), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "location_confidence", _enum("location_confidence"), server_default="unknown", nullable=False
        ),
        sa.Column(
            "resolution_method", _enum("resolution_method"), server_default="not_attempted", nullable=False
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "(latitude IS NULL) = (longitude IS NULL)", name="ck_job_locations_coordinates_are_paired"
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR (latitude BETWEEN -90 AND 90)",
            name="ck_job_locations_latitude_in_range",
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR (longitude BETWEEN -180 AND 180)",
            name="ck_job_locations_longitude_in_range",
        ),
        # The core of I1: a precision claim and coordinates must agree. A point
        # cannot be stored with `unknown` confidence, and `verified` cannot be
        # claimed without a point.
        sa.CheckConstraint(
            """
            CASE
                WHEN location_confidence IN ('verified', 'approximate')
                    THEN latitude IS NOT NULL
                WHEN location_confidence IN ('city_only', 'remote', 'unknown')
                    THEN latitude IS NULL
            END
            """,
            name="ck_job_locations_confidence_matches_coordinates",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="fk_job_locations_job_id_jobs", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_job_locations"),
    )
    op.create_index("ix_job_locations_job_id", "job_locations", ["job_id"])
    op.create_index("ix_job_locations_geom", "job_locations", ["geom"], postgresql_using="gist")
    op.create_index(
        "ix_job_locations_location_confidence", "job_locations", ["location_confidence"]
    )

    # Now that both tables exist, close the cycle. SET NULL, not CASCADE:
    # losing the denormalized pointer must never delete the job.
    op.create_foreign_key(
        "fk_jobs_primary_location_id_job_locations",
        "jobs",
        "job_locations",
        ["primary_location_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # -- job_source_links ---------------------------------------------------
    op.create_table(
        "job_source_links",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("source_job_record_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("link_reason", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "match_confidence BETWEEN 0 AND 1",
            name="ck_job_source_links_match_confidence_is_a_probability",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name="fk_job_source_links_job_id_jobs", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_job_record_id"],
            ["source_job_records.id"],
            name="fk_job_source_links_source_job_record_id_source_job_records",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_job_source_links"),
        sa.UniqueConstraint(
            "job_id",
            "source_job_record_id",
            name="uq_job_source_links_job_id_source_job_record_id",
        ),
    )

    # -- ingestion_runs -----------------------------------------------------
    op.create_table(
        "ingestion_runs",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("source_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "board_tokens",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", _enum("ingestion_run_status"), nullable=False),
        sa.Column("records_fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_closed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'running') = (finished_at IS NULL)",
            name="ck_ingestion_runs_finished_at_matches_status",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name="fk_ingestion_runs_source_id_sources",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_ingestion_runs"),
    )
    op.create_index(
        "ix_ingestion_runs_source_id_started_at", "ingestion_runs", ["source_id", "started_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_ingestion_runs_source_id_started_at", table_name="ingestion_runs")
    op.drop_table("ingestion_runs")

    op.drop_table("job_source_links")

    # Drop the cycle-closing FK before job_locations, or the drop is refused.
    op.drop_constraint("fk_jobs_primary_location_id_job_locations", "jobs", type_="foreignkey")

    op.drop_index("ix_job_locations_location_confidence", table_name="job_locations")
    op.drop_index("ix_job_locations_geom", table_name="job_locations")
    op.drop_index("ix_job_locations_job_id", table_name="job_locations")
    op.drop_table("job_locations")

    op.drop_index("ix_jobs_normalized_title", table_name="jobs")
    op.drop_index("ix_jobs_status_last_seen_at", table_name="jobs")
    op.drop_index("ix_jobs_company_id", table_name="jobs")
    op.drop_table("jobs")

    op.drop_index("ix_source_job_records_source_company_key", table_name="source_job_records")
    op.drop_index("ix_source_job_records_last_seen_at", table_name="source_job_records")
    op.drop_table("source_job_records")

    op.drop_table("sources")
    op.drop_table("companies")
    op.drop_table("users")

    # Explicit, so a second `upgrade` after a `downgrade` does not fail with
    # "type already exists". This is what makes the migration truly reversible.
    for name in reversed(list(ENUMS)):
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=False)
