"""canonical spine

Adds the three tables M1b needs: the closure audit trail, per-job embeddings,
and the merge audit trail.

Autogenerated, then corrected by hand. Autogenerate got three things wrong here
and every one of them would have failed at runtime rather than at review:

* It emitted ``pgvector.sqlalchemy.vector.VECTOR`` and
  ``nightshift.db.types.UTCDateTime`` without importing either module.
* It emitted ``sa.Enum(..., name="job_status")`` for the two status columns.
  That type already exists and is in use by ``jobs``, so the implicit
  ``CREATE TYPE`` would fail on a fresh database. Reused here as
  ``postgresql.ENUM(..., create_type=False)``, matching the approach the M0
  migration documents at its head.

The triggers are hand-written in both directions. CLAUDE.md §7 requires
append-only tables to be enforced by trigger, and a downgrade that forgets to
drop one leaves a function behind that the next upgrade quietly replaces —
working, and wrong.

Revision ID: 0002_canonical_spine
Revises: 0001_ingestion_spine
Create Date: 2026-08-01 20:09:40+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import nightshift.db.types

revision: str = "0002_canonical_spine"
down_revision: str | None = "0001_ingestion_spine"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The type already exists (created by 0001 for `jobs.status`). Reference it
# without trying to create it again.
JOB_STATUS = postgresql.ENUM(
    "open",
    "possibly_stale",
    "unverified",
    "closed",
    name="job_status",
    create_type=False,
)

APPEND_ONLY_TABLES = ("job_status_events", "job_merge_events")

APPEND_ONLY_FUNCTION = """
CREATE OR REPLACE FUNCTION nightshift_refuse_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'append-only table: % may not accept %', TG_TABLE_NAME, TG_OP;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    op.create_table(
        "job_embeddings",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        ),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_embeddings_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_embeddings")),
        sa.UniqueConstraint("job_id", name="uq_job_embeddings_job_id"),
    )
    op.create_table(
        "job_merge_events",
        sa.Column("winner_job_id", sa.UUID(), nullable=False),
        sa.Column("loser_job_id", sa.UUID(), nullable=False),
        sa.Column("loser_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("match_confidence", sa.NUMERIC(precision=4, scale=3), nullable=False),
        sa.Column("ruleset_version", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            nightshift.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "match_confidence BETWEEN 0 AND 1",
            name=op.f("ck_job_merge_events_merge_confidence_is_a_probability"),
        ),
        sa.CheckConstraint(
            "winner_job_id <> loser_job_id",
            name=op.f("ck_job_merge_events_merge_has_two_distinct_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_job_id"],
            ["jobs.id"],
            name=op.f("fk_job_merge_events_winner_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_merge_events")),
    )
    op.create_index(
        "ix_job_merge_events_winner_job_id", "job_merge_events", ["winner_job_id"], unique=False
    )
    op.create_table(
        "job_status_events",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("from_status", JOB_STATUS, nullable=True),
        sa.Column("to_status", JOB_STATUS, nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=True),
        sa.Column("observed_misses", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            nightshift.db.types.UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_job_status_events_ingestion_run_id_ingestion_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_status_events_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_status_events")),
    )
    op.create_index(
        "ix_job_status_events_job_id_created_at",
        "job_status_events",
        ["job_id", "created_at"],
        unique=False,
    )

    op.execute(APPEND_ONLY_FUNCTION)
    for table in APPEND_ONLY_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only "
            f"BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION nightshift_refuse_mutation()"
        )


def downgrade() -> None:
    for table in APPEND_ONLY_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS nightshift_refuse_mutation()")

    op.drop_index("ix_job_status_events_job_id_created_at", table_name="job_status_events")
    op.drop_table("job_status_events")
    op.drop_index("ix_job_merge_events_winner_job_id", table_name="job_merge_events")
    op.drop_table("job_merge_events")
    op.drop_table("job_embeddings")
