"""users.years_experience and users.is_enrolled — the gate's two missing inputs

Revision ID: 0014_profile_experience
Revises: 0013_role_family_and_seniority
Create Date: 2026-08-05 23:06:15.526293+00:00


The eligibility gate asks five questions and `users` could answer three. Without
these two columns `_years_rule` and `_enrollment_rule` return `cannot_tell` for
every real person forever, and the job page prints "tell us your years of
experience" beside a profile with nowhere to say it — a dead end, which is M2c's
finding about a provenance link that 404s, one milestone on.

Both nullable, because "has not told us" is a real answer and must stay distinct
from `0` and from `false`. The gate treats null as `uncertain`; it never reads it
as zero.

Neither is ever inferred. `graduation_year` is already stored and a subtraction
would produce a plausible number for both, which is exactly what invariant I2
forbids. `domain/profile.py` stays the only writer.

The check constraint is here because a negative years figure would sail through
the gate's `>=` comparison and quietly pass every experience requirement.

Autogenerate produced this one correctly, including the constraint and its
conventionalised name — which is the alembic 1.19.0 check-constraint comparator
that turned M3a's CI red now doing the job it was added for.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0014_profile_experience"
down_revision: str | None = "0013_role_family_and_seniority"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("years_experience", sa.SmallInteger(), nullable=True))
    op.add_column("users", sa.Column("is_enrolled", sa.Boolean(), nullable=True))
    op.create_check_constraint(
        op.f("ck_users_years_experience_is_not_negative"),
        "users",
        "years_experience IS NULL OR years_experience >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_years_experience_is_not_negative"), "users", type_="check")
    op.drop_column("users", "is_enrolled")
    op.drop_column("users", "years_experience")
    # ### end Alembic commands ###
